.TH "SACAM" 1
.SH NAME
SACAM \- Animal Motion Behavior Analysis System
.SH SYNOPSIS
.B sacam
[options]
.SH DESCRIPTION
SACAM stands for 'Sistema de Analise Comportamental de Animais em Movimento' in
brazilian portuguese. It was developed in CNPDIA, the Brazilian National 
Agricultural Instrumentation Center, one of the institutes of EMBRAPA, the 
Brazilian Agricultural Research Enterprise. It's main purpose is to help 
biologists in tasks such as tracking of animals in controlled environments.
It generates statistical data that is meaningful for researchers.    
.SH "SEE ALSO"
SACAM's webpage is here: http://repositorio.agrolivre.gov.br/projects/sacam/
.SH AUTHOR
SACAM was written by Luiz Irber <luiz.irber@gmail.com>