/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __SACAM_POINT_PRIVATE_H__
#define __SACAM_POINT_PRIVATE_H__

#include "sacam-point.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _SacamPointPrivate {
	gchar * start;
	gchar * end;
	gint x_pos;
	gint y_pos;
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
